Built Portfolio Setup and Mobile first
Ambient567/Portfolio-setup-and-mobile-first pull request #1
Opened 2022-08-17 22:11 UTC by Ambient567

For this project, I built the following:

The 2 sections you need to build for this project are:

    the toolbar (or header):

Toolbar

    the headline section (right after the header):

Used Flexbox in all 2 sections.
    I did not implement any functionality that requires JavaScript, like opening the menu or creating dropdowns.
    And sticked to the design as much as possible 
    Implement the button interactions (enable, hover, etc.).

2022-08-17 23:32 UTC, Ugboaja-Uchechi requested changes
Hi @Ambient567, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- Linters are passing ✔️ 
- README is descriptive 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-17 23:32 UTC, Ugboaja-Uchechi commented on index.html
> +            <ul>
- [ ] Good job with your code 👍. Kindly make sure you change the `div` with a class of `main-container` to a `header` tag this would make your code semantic and it's best practice to use a `header` tag to wrap your logo and site navigation🙏

2022-08-17 23:32 UTC, Ugboaja-Uchechi commented on index.html
> +                <li><a href="#"><i class="fa-brands fa-linkedin"></i></a></li>
- [ ] Kindly make sure you change the `div` with a class of `second-container` to a `section` tag this would make your code semantic and easy to navigate for people who depend on screen readers🙏

2022-08-17 23:32 UTC, Ugboaja-Uchechi commented on style.css
> +  }
- [ ] Please make sure your icons and background image are aligned properly as seen in the Figma design 🙏 

Figma Design | Your Design
------------- | -------------
![image](https://user-images.githubusercontent.com/74814780/185260261-cb6cecd7-1399-48f4-9bbc-112a140b6eba.png)  |  ![image](https://user-images.githubusercontent.com/74814780/185260283-815a88f2-eefd-4a62-87b4-ce5bb1bee83c.png)

2022-08-17 23:32 UTC, Ugboaja-Uchechi commented on style.css
> +
- [ ] Kindly make sure your site looks as close as possible to the Figma Design and spaced accordingly 🙏 

Figma Design | Your Design
------------- | -------------
![image](https://user-images.githubusercontent.com/74814780/185260590-62ff791a-2dea-4ce4-847d-3c3f329c6a73.png)  |  ![image](https://user-images.githubusercontent.com/74814780/185260612-5d16617a-18ca-4515-a7ba-8517c5b6a52c.png)

2022-08-17 23:32 UTC, Ugboaja-Uchechi commented on index.html
> +                <a href="#">☰ Menu</a>
- [ ] Kindly make sure the menu text isn't visible in your site.

Figma Design | Your Design
------------- | -------------
![image](https://user-images.githubusercontent.com/74814780/185260934-da1e4549-139a-4397-a005-aba4d7fc7f21.png)  |  ![image](https://user-images.githubusercontent.com/74814780/185260954-5e704bfd-881f-4c65-940f-929bab096694.png)

2022-08-17 23:32 UTC, Ugboaja-Uchechi commented on style.css
> +  background-repeat: no-repeat;
- [ ] Kindly make sure you use the appropriate `font-families` as seen in the Figma design 🙏 . You can get such `fonts` from [google fonts](https://fonts.google.com/)

2022-08-19 13:53 UTC, phelian23 requested changes
Hi @Ambient567,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.



 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 13:53 UTC, phelian23 commented on style.css
> +  }
- [ ] As requested by the previous reviewer, kindly make sure your design looks as close as possible to the Figma template. check the font sizes, font weight, and margins between each text block. Also the backgroun decoration
Your design
![Capture](https://user-images.githubusercontent.com/85095702/185633821-63664448-b424-472c-871e-91e301a53f2c.PNG)
Figma template
![figma](https://user-images.githubusercontent.com/85095702/185633883-9fce844b-0fa9-46da-b09c-b3b5bea5a7f9.PNG)

2022-08-19 20:05 UTC, ichala approved these changes
Hi @Ambient567 ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  

 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Followed Github Flow✔️
- Good commit messages ✔️
- Linters are passing ✔️
- Descriptive Pull request ✔️

Good job implementing the required changes :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
*************************************
# Optional Suggestions 

- [ ] **_Check the comments below_**


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  @ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 20:05 UTC, ichala commented on index.html
> +<body>
**_this comment is optional but highly recommended_**
- [ ]  [OPTIONAL] Great Job Implementing the required changes kindly fix this overflow to prevent users from scrolling left and right

![overflow222222](https://user-images.githubusercontent.com/89282221/185698510-c0f9ca93-d3e4-48bf-bfa0-c77288681511.gif)

2022-08-20 12:49 UTC, merged